apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: alvaronicolas-
namespace: observability
resources:
  - ../../base
secretGenerator:
  - name: grafana-cloud
    behavior: replace
    envs:
      - secret.env
